apiVersion: v1
kind: Service
metadata:
  name: eezimedz-email-service
  namespace: java
spec:
  selector:
    app: eezimedz-email-service
  ports:
    - port: 3090
      targetPort: 3090
      nodePort: 32259
  type: NodePort